import turtle as t
t.speed(0)
class Number:
    def __init__(self, d):
        self.d = d
    def zero(self):
        x = t.xcor()
        y = t.ycor()
        t.penup()
        t.forward(self.d//4)
        t.pendown()
        t.forward(self.d//2)
        t.circle(self.d//4, 180)
        t.forward(self.d//2)
        t.circle(self.d // 4, 180)
        t.penup()
        t.goto(x, y)
        t.pendown()
    def one(self):
        x = t.xcor()
        y = t.ycor()
        t.forward(self.d)
        t.left(135)
        t.forward(self.d//2)
        t.backward(self.d//2)
        t.right(135)
        t.backward(self.d)
    def two(self):
        x = t.xcor()
        y = t.ycor()
        t.right(90)
        t.forward(self.d//2)
        t.backward(self.d//2)
        t.left(45)
        t.forward(self.d//2 * 1.41)
        t.left(45)
        t.forward(self.d//4)
        t.circle(self.d//4, 180)
        t.penup()
        t.goto(x, y)
        t.pendown()
        t.left(180)
    def three(self):
        x = t.xcor()
        y = t.ycor()
        t.penup()
        t.forward(self.d)
        t.left(90)
        t.forward(self.d//4)
        t.left(180)
        t.pendown()
        t.forward(self.d//2)
        t.right(135)
        t.forward(self.d//4 * 1.6)
        t.left(45)
        t.penup()
        t.forward(self.d//4)
        t.right(90)
        t.forward(self.d//4)
        t.left(90)
        t.pendown()
        t.circle(self.d//4, 270)
        t.left(90)
        t.penup()
        t.goto(x, y)
        t.pendown()
        t.left(180)
    def four(self):
        x = t.xcor()
        y = t.ycor()
        t.forward(self.d//2)
        t.penup()
        t.forward(self.d//2)
        t.left(146)
        t.pendown()
        t.forward(3.6 *self.d //4)
        t.left(124)
        t.forward(self.d//2)
        t.right(90)
        t.forward(self.d//4)
        t.left(180)
        t.penup()
        t.goto(x, y)
        t.pendown()
    def five(self):
        x = t.xcor()
        y = t.ycor()
        t.right(90)
        t.circle(self.d//3, 180)
        t.right(90)
        t.forward(self.d//3)
        t.right(90)
        t.forward(self.d//3)
        t.right(90)
        t.penup()
        t.goto(x, y)
        t.pendown()
        t.left(180)
    def six(self):
        x = t.xcor()
        y = t.ycor()
        t.penup()
        t.forward(self.d)
        t.pendown()
        t.left(150)
        t.forward(self.d//4 * 3)
        t.circle(self.d//4)
        t.circle(self.d//4, 120)
        t.left(90)
        t.penup()
        t.goto(x, y)
        t.pendown()
    def seven(self):
        x = t.xcor()
        y = t.ycor()
        t.right(90)
        t.left(70)
        t.forward(self.d)
        t.left(110)
        t.forward(self.d//2)
        t.left(90)
        t.penup()
        t.forward(self.d)
        t.left(90)
        t.forward(self.d//2)
        t.pendown()
        t.left(90)
        t.penup()
        t.goto(x, y)
        t.pendown()
    def eight(self):
        x = t.xcor()
        y = t.ycor()
        t.penup()
        t.forward(self.d//2)
        t.right(90)
        t.pendown()
        t.circle(self.d//4)
        t.left(180)
        t.circle(self.d//4)
        t.left(90)
        t.penup()
        t.forward(self.d//2)
        t.pendown()
        t.right(90)
        t.left(180)
        t.left(90)
        t.penup()
        t.goto(x, y)
        t.pendown()
    def nine(self):
        x = t.xcor()
        y = t.ycor()
        t.right(90)
        t.left(70)
        t.forward(self.d)
        t.circle(self.d//2)
        t.backward(self.d)
        t.right(70)
        t.left(90)
        t.penup()
        t.goto(x, y)
        t.pendown()
    def ten(self):
        x = t.xcor()
        y = t.ycor()
        self.one()
        t.penup()
        t.right(90)
        t.forward(self.d //4 * 3)
        t.pendown()
        t.left(90)
        self.zero()
        t.penup()
        t.goto(x, y)
        t.pendown()
    def eleven(self):
        x = t.xcor()
        y = t.ycor()
        self.one()
        t.penup()
        t.right(90)
        t.forward(self.d // 4 * 3)
        t.pendown()
        t.left(90)
        self.one()
        t.penup()
        t.goto(x, y)
        t.pendown()
    def twelve(self):
        x = t.xcor()
        y = t.ycor()
        self.one()
        t.penup()
        t.right(90)
        t.forward(self.d // 2)
        t.pendown()
        t.left(90)
        self.two()
        t.penup()
        t.goto(x, y)
        t.pendown()
class Clock:
    def __init__(self, d):
        self.d = d
    def draw(self):
        x = t.xcor()
        y = t.ycor()
        t.penup()
        t.backward(self.d//2)
        t.pendown()
        t.right(90)
        t.circle(self.d//2)
        t.left(90)
        t.penup()
        t.forward(self.d //12 * 11)
        t.pendown()
        n = Number(self.d // 15)

        n.twelve()
        t.penup()
        t.left(90)
        t.forward(self.d // 6)
        t.right(90)
        t.backward(self.d // 12)
        t.pendown()

        n.eleven()
        t.penup()
        t.left(90)
        t.forward(self.d // 6)
        t.right(90)
        t.backward(self.d // 8)
        t.pendown()

        n.ten()
        t.penup()
        t.left(90)
        t.forward(self.d // 12)
        t.right(90)
        t.backward(self.d // 4)
        t.pendown()

        n.nine()
        t.penup()
        t.left(90)
        t.backward(self.d // 12)
        t.right(90)
        t.backward(self.d // 6)
        t.pendown()

        n.eight()
        t.penup()
        t.left(90)
        t.backward(self.d // 6)
        t.right(90)
        t.backward(self.d // 6)
        t.pendown()

        n.seven()
        t.penup()
        t.left(90)
        t.backward(self.d // 6)
        t.right(90)
        t.backward(self.d // 12)
        t.pendown()

        n.six()
        t.penup()
        t.left(90)
        t.backward(self.d // 6)
        t.right(90)
        t.forward(self.d // 12)
        t.pendown()

        n.five()
        t.penup()
        t.left(90)
        t.backward(self.d // 6)
        t.right(90)
        t.forward(self.d // 8)
        t.pendown()

        n.four()
        t.penup()
        t.left(90)
        t.backward(self.d // 8)
        t.right(90)
        t.forward(self.d // 6)
        t.pendown()

        n.three()
        t.penup()
        t.left(90)
        t.forward(self.d // 8)
        t.right(90)
        t.forward(self.d // 4)
        t.pendown()

        n.two()
        t.penup()
        t.left(90)
        t.forward(self.d // 6)
        t.right(90)
        t.forward(self.d // 6)
        t.pendown()

        n.one()
        t.penup()
        t.goto(x, y)
        t.pendown()

        t.forward(self.d // 4)
        t.backward(self.d // 4)
class Direct:
    def __init__(self, d):
        self.d = d
    def _dir(self, gradus = 0, color = "black"):
        t.left(gradus)
        t.color(color)
        t.forward(self.d//4)
        t.backward(self.d//4)
    def draw(self):
        h = 0
        m = 0
        s = 0
        while True:
            t.delay(100)
            self._dir(s,"white")
            self._dir(6)
            s += 6
            t.right(s)
            self._dir(m, "white")
            self._dir(0.1)
            m += 0.1
            t.right(m)






c = Clock(200)
n = Number(100)
d = Direct(200)
t.left(90)
#n.twelve()
c.draw()
d.draw()
t.mainloop()